import requests

# SQL query generated by AI
sql = "SELECT * FROM users"

# Send SQL to backend API
response = requests.post(
    "http://localhost:3000/query",
    json={"sql": sql}
)

# Print API response
print(response.json())